services:
  amazonlinux-ssh:
    image: amazonlinux-ssh
    build: amazonlinux-ssh
    container_name: amazonlinux-ssh
    ports:
      - "2222:22"
  amazonlinux-ansible:
    image: amazonlinux-ansible
    build: amazonlinux-ansible
    container_name: amazonlinux-ansible
    links:
      - "amazonlinux-ssh"
    #    entrypoint: ["ansible", "amazonlinux-ssh", "-m", "ping"]
    entrypoint: ["ping", "amazonlinux-ssh"]
    depends_on:
      - amazonlinux-ssh