services:
  amazonlinux-ansible:
    image: amazonlinux-ansible
    build: amazonlinux-ansible
    container_name: amazonlinux-ansible
    entrypoint: ["ansible", "all", "-m", "ping", "-i", "inventory"]
    depends_on:
      - alpine-sshd
  alpine-sshd:
    image: alpine-sshd
    build: alpine-sshd
    container_name: alpine-sshd
    ports:
      - 22